server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.skydemo.mybatis.entity

spring:
  datasource:
    url: jdbc:mysql://121.37.11.215:3306/sky-mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
#    password: 123456
    password: U2jbmZXTVK
    driver-class-name: com.mysql.cj.jdbc.Driver

prop:
  druidDataSourceConfig:
    error-retry: 3
    error-retry-interval: 5000
    breakafteracquirefailure: true
    maxwait: 10000
    maxactive: 20