server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.skydemo.mybatis.entity

spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#dynamicdatasource:
#  default-datasource:
#    jdbcUrl: jdbc:mysql://localhost:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  sales-datasource:
#    jdbcUrl: jdbc:mysql://localhost:3306/sys-test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver